#ifndef ERROR_H_
#define ERROR_H_

#include <stdio.h>

typedef enum {
    VM_SUCCESS = 0,
    VM_ERROR_INITIALIZATION,
    VM_ERROR_INVALID_ARGUMENT,
    VM_ERROR_INVALID_INSTRUCTION,
    VM_ERROR_INVALID_OPERAND,
    VM_ERROR_STACK_OVERFLOW,
    VM_ERROR_STACK_UNDERFLOW,
    VM_ERROR_DIVIDE_BY_ZERO,
    VM_ERROR_MEMORY_ACCESS,
    VM_ERROR_MEMORY_INIT,
    VM_ERROR_INVALID_LABEL,
    VM_ERROR_INVALID_REGISTER,
    VM_ERROR_PROGRAM_COUNTER_OUT_OF_BOUNDS,
    VM_ERROR_MEMORY_ALREADY_INITIALIZED,
    VM_ERROR_UNKNOWN
} VMError;

int handle_error(VMError err);

#endif  // ERROR_H_
